# Generated by Django 2.2.6 on 2019-11-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0005_auto_20191115_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='gpa',
            field=models.FloatField(default=0),
        ),
    ]
