# Generated by Django 2.2.7 on 2019-11-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='subject',
            field=models.CharField(default='math', max_length=50),
        ),
        migrations.AlterField(
            model_name='grades',
            name='english',
            field=models.PositiveIntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='grades',
            name='japanese',
            field=models.PositiveIntegerField(default=70),
        ),
        migrations.AlterField(
            model_name='grades',
            name='math',
            field=models.PositiveIntegerField(default=66),
        ),
    ]
