# Generated by Django 2.2.6 on 2019-11-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='gpa',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grades',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='grades',
            name='english',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='grades',
            name='japanese',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='grades',
            name='math',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
