# Generated by Django 2.2.7 on 2019-11-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_auto_20191114_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='english',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='grades',
            name='japanese',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='grades',
            name='math',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='grades',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
