# Generated by Django 2.2.6 on 2019-11-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_auto_20191113_1544'),
        ('grades', '0003_auto_20191115_0019'),
    ]

    operations = [
    ]
